### ISSUE TITLE
APP may not startup when Android version low than Android P

### ISSUE THREAD

**Issue by CoNETProject** [QTGate/CoNETPlatform-Android#1]
Issue: 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ca.conettech.conetplatformandroid, PID: 3676
    java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libnode.so" needed by "/data/app/ca.conettech.conetplatformandroid-1/lib/x86_64/libnative-lib.so"; caused by cannot locate symbol "_Unwind_Backtrace" referenced by "libnode.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:989)
        at ca.conettech.conetplatformandroid.MainActivity.<clinit>(MainActivity.java:25)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1572)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by QianhZ8972** [comment]
我的下载了就不能安装

**Comment by CoNETProject** [comment]
Fixed.
